#!/bin/sh

DIR=/etc/jarred
HOSTDIR=./tmp

cat <<END
<!DOCTYPE html>
<html>
    <head>
        <title>Statistics Index</title>
    </head>
    <body>
        <h1>All Statistics</h1>

        <h2>Presets</h2>
        <ul id="presets">
END

for fn in $DIR/*.js; do
    name=${fn#$DIR/}
    name=${name%.js}
    echo '            <li><a href="/'$name'.html">'$name'</a></li>'
done

cat <<END
        </ul>

        <h2>Servers</h2>
        <ul id="servers">
END

for fn in $HOSTDIR/*; do
    name=${fn#$HOSTDIR/}
    name=${name%.js}
    echo '            <li><a href="/'$name'.html">'$name'</a></li>'
done

cat <<END
        </ul>

    </body>
</html>
END
